autocmd FileType ruby compiler ruby

set showmatch  " show matching braces when text indicator is over them
set hidden " the best switch in buffers
" set number  line number
" set relativenumber relative number
set novisualbell " no blink
set noerrorbells " sound bells
set t_vb=
set visualbell t_vb=
set mouse=a " enable mouse
set mousehide " mousehide when insert text
set encoding=utf-8
scriptencoding utf-8
 
" Set paddings top and bottom
set  winheight=5 winminheight=5

" Set the commands to save in history default number is 20
set history=6000

" Highlight cursor line underneath the cursor horizontally
" set cursorline
" Highlight cursor line underneath the cursor vertically
" set cursorcolumn


set ttimeout
set ttimeoutlen=1
set ttyfast

" Settings cursor mode
"  1 -> blinking block
"  2 -> solid block 
"  3 -> blinking underscore
"  4 -> solid underscore
"  5 -> blinking vertical bar
"  6 -> solid vertical bar
let &t_EI = "\<Esc>[2 q" " Normal mode
let &t_SR = "\<Esc>[4 q" " Replace mode
let &t_SI = "\<Esc>[6 q" " Insert mode

set wrap " wrap or nowrap
set colorcolumn=78 " set highlight column
hi ColorColumn ctermbg=DarkGray
set scrolloff=3
set iminsert=0 " ignoring registr in search
set hlsearch " highling search
set incsearch " highling search
" use 2 spaces instead of tabs during formatting
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
" open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

set linebreak " wrap on word
set smartindent " for tabulation
set nocompatible	" not vi compatible
set ruler
set incsearch
set showcmd " show enter command
set nobackup " no .swap and backup files
set noswapfile
set fileencodings=utf8,cp1251
set backspace=indent,eol,start whichwrap+=<,>,[,] " cool using backspace
set showtabline=1 " no show hr tab
set clipboard=unnamed

set laststatus=0
set noshowmode
set noshowcmd

set autoindent
syntax on " highlight syntax on
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins

" START SETTINGS PLUGINS— — — — — — — — — — — — — — — — — — — — — — — — — — —

call plug#begin('~/.vim/plugged')

Plug 'dracula/vim', { 'as': 'dracula' }

Plug 'vim-ruby/vim-ruby'

" A command-line fuzzy finder.
" Doc: https://github.com/junegunn/fzf
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Distraction-free writing in Vim
" Doc: https://github.com/junegunn/goyo.vim
Plug 'junegunn/goyo.vim'

" Seamless navigation between tmux panes and vim splits
" Doc: https://github.com/christoomey/vim-tmux-navigator
Plug 'christoomey/vim-tmux-navigator'

" Vim and tmux, sittin' in a tree...
" Doc: https://github.com/christoomey/vim-tmux-runner
Plug 'christoomey/vim-tmux-runner'

" Vim plugin for copying to the system clipboard with text-objects and motions
" Doc: https://github.com/christoomey/vim-system-copy
Plug 'christoomey/vim-system-copy'

" A tree explorer plugin for Vim. Doc: https://github.com/preservim/nerdtree
Plug 'preservim/nerdtree'

" Emmet for vim. Doc:
" https://github.com/mattn/emmet-vim
" https://emmet.io
Plug 'mattn/emmet-vim'

" fugitive.vim: A Git wrapper so awesome, it should be illegal
" Doc: https://github.com/tpope/vim-fugitive
Plug 'tpope/vim-fugitive'

" Delete/change/add parentheses/quotes/XML-tags/much more with ease
" Doc: https://github.com/tpope/vim-surround
Plug 'tpope/vim-surround'

" Commentary in Vim. Doc: https://github.com/tpope/vim-surround
Plug 'tpope/vim-commentary'

" Provides the branch name of the current git repository
" Doc:	https://github.com/itchyny/vim-gitbranch
Plug 'itchyny/vim-gitbranch'

" A Vim plugin which saves files to disk automatically.
" Doc: https://github.com/907th/vim-auto-save
Plug '907th/vim-auto-save'

" Perform all your vim insert mode completions with Tab
" Doc: https://github.com/maxdzyubak/supertab 
Plug 'ervandew/supertab'

" Multiple cursors plugin for vim/neovim
" Doc: https://github.com/mg979/vim-visual-multi
" Plug 'mg979/vim-visual-multi', {'branch': 'master'}

Plug 'w0rp/ale'


Plug 'jiangmiao/auto-pairs'

call plug#end()

" END SETTINGS PLUGINS— — — — — — — — — — — — — — — — — — — — — — — — — — — —

" Show all hidden files in NERDTree
let NERDTreeShowHidden=1

" set background=dark	 Setting dark mode
" set background=light	 Setting light mode

set termguicolors

colorscheme dracula 

" enable emmet
let g:user_emmet_mode='a'  "enable all function in all mode.

let g:auto_save = 1  " enable AutoSave on Vim startup
let g:auto_save_silent = 1  " do not display the auto-save notification

" START SETTINGS MAPPINGS — — — — — — — — — — — — — — — — — — — — — — — — — —

" set mapleader is space
let mapleader = " "

 " j  + j  = esc
inoremap jj <esc>

" Save file
nmap <leader>s :w!<cr>

" Quit vim with dont save
nmap <leader>q :q!<cr> 

" set :noh
nmap <leader>/ :noh<cr>

" Quit vim with save
nmap <leader>sq :wq<cr> 

" Yank from cursor to the end of line.
nnoremap Y y$

" Set big J and big K to 5 line top and bottom
nnoremap J 5j
nnoremap K 5k

" set emmet-vim plugin key trigger
imap kk <C-y>,

imap <C-"> <c-s-t>"
imap <C-'> <d-s>"

" open and close NERDTree
map <Leader><space> :NERDTreeToggle<cr>
map <C-n> :NERDTreeFind<cr>

" Use ctrl-[hjkl] to select the active split!
" nmap <silent> <c-k> :wincmd k<CR>
" nmap <silent> <c-j> :wincmd j<CR>
" nmap <silent> <c-h> :wincmd h<CR>
" nmap <silent> <c-l> :wincmd l<CR>

" Toggle plug goyo
nmap <leader>p :Goyo<cr>

let g:tmux_navigator_no_mappings = 1

noremap <silent> {Left-Mapping} :<C-U>TmuxNavigateLeft<cr>
noremap <silent> {Down-Mapping} :<C-U>TmuxNavigateDown<cr>
noremap <silent> {Up-Mapping} :<C-U>TmuxNavigateUp<cr>
noremap <silent> {Right-Mapping} :<C-U>TmuxNavigateRight<cr>
noremap <silent> {Previous-Mapping} :<C-U>TmuxNavigatePrevious<cr>

" Set maps in Vim Tmux Runner
nmap <leader>or :VtrOpenRunner {'orientation': 'h', 'percentage': 43, 'cmd': 'irb'}<cr>
nmap <leader>r :VtrSendCommandToRunner !ruby %<cr>
nmap <leader>kr :VtrKillRunner<cr>
nmap <leader>fr :VtrFocusRunner<cr>

" Fzf keybindings
nnoremap <silent> <Leader>f :BLines<CR>
" END SETTINGS MAPPINGS — — — — — — — — — — — — — — — — — — — — — — — — — — —
